
project_id = "rbhzesocmhazynkfyhst"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.send-temp-password]
verify_jwt = false

